/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";
import type { ZeroCustomType } from "drizzle-zero";
import type { default as zeroSchema } from "../drizzle-zero.config";

const adminNoteTable = {
  name: "adminNote",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "adminNote",
        "id"
      >,
    },
    feedbackId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "adminNote",
        "feedbackId"
      >,
      serverName: "feedback_id",
    },
    authorId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "adminNote",
        "authorId"
      >,
      serverName: "author_id",
    },
    body: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "adminNote",
        "body"
      >,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "adminNote",
        "createdAt"
      >,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "adminNote",
        "updatedAt"
      >,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "admin_note",
} as const;
const boardTable = {
  name: "board",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "board",
        "id"
      >,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "board",
        "organizationId"
      >,
      serverName: "organization_id",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "board",
        "name"
      >,
    },
    slug: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "board",
        "slug"
      >,
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "board",
        "description"
      >,
    },
    isPublic: {
      type: "boolean",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "board",
        "isPublic"
      >,
      serverName: "is_public",
    },
    settings: {
      type: "json",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "board",
        "settings"
      >,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "board",
        "createdAt"
      >,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "board",
        "updatedAt"
      >,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const commentTable = {
  name: "comment",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "comment",
        "id"
      >,
    },
    feedbackId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "comment",
        "feedbackId"
      >,
      serverName: "feedback_id",
    },
    authorId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "comment",
        "authorId"
      >,
      serverName: "author_id",
    },
    body: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "comment",
        "body"
      >,
    },
    isOfficial: {
      type: "boolean",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "comment",
        "isOfficial"
      >,
      serverName: "is_official",
    },
    parentId: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "comment",
        "parentId"
      >,
      serverName: "parent_id",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "comment",
        "createdAt"
      >,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "comment",
        "updatedAt"
      >,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const feedbackTable = {
  name: "feedback",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "feedback",
        "id"
      >,
    },
    boardId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "feedback",
        "boardId"
      >,
      serverName: "board_id",
    },
    title: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "feedback",
        "title"
      >,
    },
    description: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "feedback",
        "description"
      >,
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "feedback",
        "status"
      >,
    },
    authorId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "feedback",
        "authorId"
      >,
      serverName: "author_id",
    },
    voteCount: {
      type: "number",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "feedback",
        "voteCount"
      >,
      serverName: "vote_count",
    },
    commentCount: {
      type: "number",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "feedback",
        "commentCount"
      >,
      serverName: "comment_count",
    },
    isApproved: {
      type: "boolean",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "feedback",
        "isApproved"
      >,
      serverName: "is_approved",
    },
    isPinned: {
      type: "boolean",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "feedback",
        "isPinned"
      >,
      serverName: "is_pinned",
    },
    roadmapLane: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "feedback",
        "roadmapLane"
      >,
      serverName: "roadmap_lane",
    },
    roadmapOrder: {
      type: "number",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "feedback",
        "roadmapOrder"
      >,
      serverName: "roadmap_order",
    },
    completedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "feedback",
        "completedAt"
      >,
      serverName: "completed_at",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "feedback",
        "createdAt"
      >,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "feedback",
        "updatedAt"
      >,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const feedbackTagTable = {
  name: "feedbackTag",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "feedbackTag",
        "id"
      >,
    },
    feedbackId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "feedbackTag",
        "feedbackId"
      >,
      serverName: "feedback_id",
    },
    tagId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "feedbackTag",
        "tagId"
      >,
      serverName: "tag_id",
    },
  },
  primaryKey: ["id"],
  serverName: "feedback_tag",
} as const;
const invitationTable = {
  name: "invitation",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "invitation",
        "id"
      >,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "invitation",
        "organizationId"
      >,
    },
    email: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "invitation",
        "email"
      >,
    },
    role: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "invitation",
        "role"
      >,
    },
    status: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "invitation",
        "status"
      >,
    },
    expiresAt: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "invitation",
        "expiresAt"
      >,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "invitation",
        "createdAt"
      >,
    },
    inviterId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "invitation",
        "inviterId"
      >,
    },
  },
  primaryKey: ["id"],
} as const;
const memberTable = {
  name: "member",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "member",
        "id"
      >,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "member",
        "organizationId"
      >,
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "member",
        "userId"
      >,
    },
    role: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "member",
        "role"
      >,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "member",
        "createdAt"
      >,
    },
  },
  primaryKey: ["id"],
} as const;
const notificationTable = {
  name: "notification",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "notification",
        "id"
      >,
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "notification",
        "userId"
      >,
      serverName: "user_id",
    },
    type: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "notification",
        "type"
      >,
    },
    title: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "notification",
        "title"
      >,
    },
    message: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "notification",
        "message"
      >,
    },
    feedbackId: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "notification",
        "feedbackId"
      >,
      serverName: "feedback_id",
    },
    isRead: {
      type: "boolean",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "notification",
        "isRead"
      >,
      serverName: "is_read",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "notification",
        "createdAt"
      >,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
} as const;
const organizationTable = {
  name: "organization",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "organization",
        "id"
      >,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "organization",
        "name"
      >,
    },
    slug: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "organization",
        "slug"
      >,
    },
    logo: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "organization",
        "logo"
      >,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "organization",
        "createdAt"
      >,
    },
    metadata: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "organization",
        "metadata"
      >,
    },
    primaryColor: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "organization",
        "primaryColor"
      >,
      serverName: "primary_color",
    },
    customCss: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "organization",
        "customCss"
      >,
      serverName: "custom_css",
    },
    isPublic: {
      type: "boolean",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "organization",
        "isPublic"
      >,
      serverName: "is_public",
    },
  },
  primaryKey: ["id"],
} as const;
const releaseTable = {
  name: "release",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "release",
        "id"
      >,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "release",
        "organizationId"
      >,
      serverName: "organization_id",
    },
    title: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "release",
        "title"
      >,
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "release",
        "description"
      >,
    },
    version: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "release",
        "version"
      >,
    },
    publishedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "release",
        "publishedAt"
      >,
      serverName: "published_at",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "release",
        "createdAt"
      >,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "release",
        "updatedAt"
      >,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const releaseItemTable = {
  name: "releaseItem",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "releaseItem",
        "id"
      >,
    },
    releaseId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "releaseItem",
        "releaseId"
      >,
      serverName: "release_id",
    },
    feedbackId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "releaseItem",
        "feedbackId"
      >,
      serverName: "feedback_id",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "releaseItem",
        "createdAt"
      >,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "release_item",
} as const;
const tagTable = {
  name: "tag",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "tag",
        "id"
      >,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "tag",
        "organizationId"
      >,
      serverName: "organization_id",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "tag",
        "name"
      >,
    },
    color: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "tag",
        "color"
      >,
    },
    isDoneStatus: {
      type: "boolean",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "tag",
        "isDoneStatus"
      >,
      serverName: "is_done_status",
    },
    isRoadmapLane: {
      type: "boolean",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "tag",
        "isRoadmapLane"
      >,
      serverName: "is_roadmap_lane",
    },
    laneOrder: {
      type: "number",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "tag",
        "laneOrder"
      >,
      serverName: "lane_order",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "tag",
        "createdAt"
      >,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
} as const;
const userTable = {
  name: "user",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "user",
        "id"
      >,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "user",
        "name"
      >,
    },
    email: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "user",
        "email"
      >,
    },
    emailVerified: {
      type: "boolean",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "user",
        "emailVerified"
      >,
    },
    image: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "user",
        "image"
      >,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "user",
        "createdAt"
      >,
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "user",
        "updatedAt"
      >,
    },
    partner: {
      type: "boolean",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "user",
        "partner"
      >,
    },
    avatar: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "user",
        "avatar"
      >,
    },
    bio: {
      type: "string",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "user",
        "bio"
      >,
    },
    bannedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "user",
        "bannedAt"
      >,
      serverName: "banned_at",
    },
  },
  primaryKey: ["id"],
} as const;
const voteTable = {
  name: "vote",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "vote",
        "id"
      >,
    },
    feedbackId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "vote",
        "feedbackId"
      >,
      serverName: "feedback_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "vote",
        "userId"
      >,
      serverName: "user_id",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as ZeroCustomType<
        typeof zeroSchema,
        "vote",
        "createdAt"
      >,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
} as const;
const feedbackRelationships = {
  tags: [
    {
      sourceField: ["id"],
      destField: ["feedbackId"],
      destSchema: "feedbackTag",
      cardinality: "many",
    },
    {
      sourceField: ["tagId"],
      destField: ["id"],
      destSchema: "tag",
      cardinality: "many",
    },
  ],
  releases: [
    {
      sourceField: ["id"],
      destField: ["feedbackId"],
      destSchema: "releaseItem",
      cardinality: "many",
    },
    {
      sourceField: ["releaseId"],
      destField: ["id"],
      destSchema: "release",
      cardinality: "many",
    },
  ],
  board: [
    {
      sourceField: ["boardId"],
      destField: ["id"],
      destSchema: "board",
      cardinality: "one",
    },
  ],
  author: [
    {
      sourceField: ["authorId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  votes: [
    {
      sourceField: ["id"],
      destField: ["feedbackId"],
      destSchema: "vote",
      cardinality: "many",
    },
  ],
  comments: [
    {
      sourceField: ["id"],
      destField: ["feedbackId"],
      destSchema: "comment",
      cardinality: "many",
    },
  ],
  feedbackTags: [
    {
      sourceField: ["id"],
      destField: ["feedbackId"],
      destSchema: "feedbackTag",
      cardinality: "many",
    },
  ],
  adminNotes: [
    {
      sourceField: ["id"],
      destField: ["feedbackId"],
      destSchema: "adminNote",
      cardinality: "many",
    },
  ],
  releaseItems: [
    {
      sourceField: ["id"],
      destField: ["feedbackId"],
      destSchema: "releaseItem",
      cardinality: "many",
    },
  ],
} as const;
const tagRelationships = {
  feedbacks: [
    {
      sourceField: ["id"],
      destField: ["tagId"],
      destSchema: "feedbackTag",
      cardinality: "many",
    },
    {
      sourceField: ["feedbackId"],
      destField: ["id"],
      destSchema: "feedback",
      cardinality: "many",
    },
  ],
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  feedbackTags: [
    {
      sourceField: ["id"],
      destField: ["tagId"],
      destSchema: "feedbackTag",
      cardinality: "many",
    },
  ],
} as const;
const releaseRelationships = {
  feedbacks: [
    {
      sourceField: ["id"],
      destField: ["releaseId"],
      destSchema: "releaseItem",
      cardinality: "many",
    },
    {
      sourceField: ["feedbackId"],
      destField: ["id"],
      destSchema: "feedback",
      cardinality: "many",
    },
  ],
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  releaseItems: [
    {
      sourceField: ["id"],
      destField: ["releaseId"],
      destSchema: "releaseItem",
      cardinality: "many",
    },
  ],
} as const;
const adminNoteRelationships = {
  feedback: [
    {
      sourceField: ["feedbackId"],
      destField: ["id"],
      destSchema: "feedback",
      cardinality: "one",
    },
  ],
  author: [
    {
      sourceField: ["authorId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const boardRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  feedbacks: [
    {
      sourceField: ["id"],
      destField: ["boardId"],
      destSchema: "feedback",
      cardinality: "many",
    },
  ],
} as const;
const commentRelationships = {
  feedback: [
    {
      sourceField: ["feedbackId"],
      destField: ["id"],
      destSchema: "feedback",
      cardinality: "one",
    },
  ],
  author: [
    {
      sourceField: ["authorId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  parent: [
    {
      sourceField: ["parentId"],
      destField: ["id"],
      destSchema: "comment",
      cardinality: "one",
    },
  ],
  replies: [
    {
      sourceField: ["id"],
      destField: ["parentId"],
      destSchema: "comment",
      cardinality: "many",
    },
  ],
} as const;
const feedbackTagRelationships = {
  feedback: [
    {
      sourceField: ["feedbackId"],
      destField: ["id"],
      destSchema: "feedback",
      cardinality: "one",
    },
  ],
  tag: [
    {
      sourceField: ["tagId"],
      destField: ["id"],
      destSchema: "tag",
      cardinality: "one",
    },
  ],
} as const;
const invitationRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  inviter: [
    {
      sourceField: ["inviterId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const memberRelationships = {
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
} as const;
const notificationRelationships = {
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  feedback: [
    {
      sourceField: ["feedbackId"],
      destField: ["id"],
      destSchema: "feedback",
      cardinality: "one",
    },
  ],
} as const;
const organizationRelationships = {
  members: [
    {
      sourceField: ["id"],
      destField: ["organizationId"],
      destSchema: "member",
      cardinality: "many",
    },
  ],
  invitations: [
    {
      sourceField: ["id"],
      destField: ["organizationId"],
      destSchema: "invitation",
      cardinality: "many",
    },
  ],
  boards: [
    {
      sourceField: ["id"],
      destField: ["organizationId"],
      destSchema: "board",
      cardinality: "many",
    },
  ],
  tags: [
    {
      sourceField: ["id"],
      destField: ["organizationId"],
      destSchema: "tag",
      cardinality: "many",
    },
  ],
  releases: [
    {
      sourceField: ["id"],
      destField: ["organizationId"],
      destSchema: "release",
      cardinality: "many",
    },
  ],
} as const;
const releaseItemRelationships = {
  release: [
    {
      sourceField: ["releaseId"],
      destField: ["id"],
      destSchema: "release",
      cardinality: "one",
    },
  ],
  feedback: [
    {
      sourceField: ["feedbackId"],
      destField: ["id"],
      destSchema: "feedback",
      cardinality: "one",
    },
  ],
} as const;
const userRelationships = {
  members: [
    {
      sourceField: ["id"],
      destField: ["userId"],
      destSchema: "member",
      cardinality: "many",
    },
  ],
  feedbacks: [
    {
      sourceField: ["id"],
      destField: ["authorId"],
      destSchema: "feedback",
      cardinality: "many",
    },
  ],
  votes: [
    {
      sourceField: ["id"],
      destField: ["userId"],
      destSchema: "vote",
      cardinality: "many",
    },
  ],
  comments: [
    {
      sourceField: ["id"],
      destField: ["authorId"],
      destSchema: "comment",
      cardinality: "many",
    },
  ],
  notifications: [
    {
      sourceField: ["id"],
      destField: ["userId"],
      destSchema: "notification",
      cardinality: "many",
    },
  ],
} as const;
const voteRelationships = {
  feedback: [
    {
      sourceField: ["feedbackId"],
      destField: ["id"],
      destSchema: "feedback",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    adminNote: adminNoteTable,
    board: boardTable,
    comment: commentTable,
    feedback: feedbackTable,
    feedbackTag: feedbackTagTable,
    invitation: invitationTable,
    member: memberTable,
    notification: notificationTable,
    organization: organizationTable,
    release: releaseTable,
    releaseItem: releaseItemTable,
    tag: tagTable,
    user: userTable,
    vote: voteTable,
  },
  relationships: {
    feedback: feedbackRelationships,
    tag: tagRelationships,
    release: releaseRelationships,
    adminNote: adminNoteRelationships,
    board: boardRelationships,
    comment: commentRelationships,
    feedbackTag: feedbackTagRelationships,
    invitation: invitationRelationships,
    member: memberRelationships,
    notification: notificationRelationships,
    organization: organizationRelationships,
    releaseItem: releaseItemRelationships,
    user: userRelationships,
    vote: voteRelationships,
  },
  enableLegacyQueries: true,
  enableLegacyMutators: true,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "adminNote" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type AdminNote = Row<typeof adminNoteTable>;
/**
 * Represents a row from the "board" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Board = Row<typeof boardTable>;
/**
 * Represents a row from the "comment" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Comment = Row<typeof commentTable>;
/**
 * Represents a row from the "feedback" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Feedback = Row<typeof feedbackTable>;
/**
 * Represents a row from the "feedbackTag" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type FeedbackTag = Row<typeof feedbackTagTable>;
/**
 * Represents a row from the "invitation" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Invitation = Row<typeof invitationTable>;
/**
 * Represents a row from the "member" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Member = Row<typeof memberTable>;
/**
 * Represents a row from the "notification" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Notification = Row<typeof notificationTable>;
/**
 * Represents a row from the "organization" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Organization = Row<typeof organizationTable>;
/**
 * Represents a row from the "release" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Release = Row<typeof releaseTable>;
/**
 * Represents a row from the "releaseItem" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ReleaseItem = Row<typeof releaseItemTable>;
/**
 * Represents a row from the "tag" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Tag = Row<typeof tagTable>;
/**
 * Represents a row from the "user" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<typeof userTable>;
/**
 * Represents a row from the "vote" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Vote = Row<typeof voteTable>;

/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = createBuilder(schema);
